name: Terraform Infra (emp-etl)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        type: choice
        options:
          - dev
          - prod
      action:
        description: "Select action"
        required: true
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest

    environment: ${{ github.event.inputs.environment }}

    defaults:
      run:
        working-directory: emp-etl/infra

    steps:
      # 1️⃣ Checkout
      - name: Checkout
        uses: actions/checkout@v3

      # 2️⃣ Authenticate GCP
      - name: Authenticate GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      # 3️⃣ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 4️⃣ Init (always)
      - name: Terraform Init
        run: terraform init

      # 5️⃣ Plan (always before apply/destroy)
      - name: Terraform Plan
        run: terraform plan -var-file="env/${{ github.event.inputs.environment }}.tfvars"

      # 6️⃣ Apply
      - name: Terraform Apply
        if: github.event.inputs.action == 'apply'
        run: terraform apply -auto-approve -var-file="env/${{ github.event.inputs.environment }}.tfvars"

      # 7️⃣ Destroy
      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve -var-file="env/${{ github.event.inputs.environment }}.tfvars"